#!/bin/bash

#list aliases
alias ls='ls --all --color=auto --group-directories-first'
alias l='ls -l'

# exa
alias exa='exa --color=automatic --all --sort=Name --group-directories-first'
alias e='exa --long'

# grep
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# pipe command output to clipboard
alias copy='xclip -sel clip'

# shortcuts
alias q='exit'
alias v='nvim'
