#!/usr/bin/env bash

#list aliases
alias ls='ls --all --color=auto --group-directories-first'
alias l='ls -l'

# exa
if type exa > /dev/null 2>&1; then
  alias exa='exa --color=automatic --all --sort=Name --group-directories-first'
  alias e='exa --long'
fi

# grep
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# pipe command output to clipboard
if type xclip > /dev/null 2>&1; then
  alias copy='xclip -sel clip'
fi

# shortcuts
alias q='exit'
alias v='nvim'

if type kubectl > /dev/null 2>&1; then
  alias k='kubectl'
fi
if type terraform > /dev/null 2>&1; then
  alias tf='terraform'
fi
if type docker > /dev/null 2>&1; then
  alias d='docker'
fi

# list content after cd
if type exa > /dev/null 2>&1; then
  function cd () {
    builtin cd "$@" && exa
  }
else
  function cd () {
    builtin cd "$@" && ls
  }
fi

# keyboard layouts
alias nocaps='setxkbmap -option "ctrl:nocaps"'
alias qwer='setxkbmap fr'
alias azer='setxkbmap us'
