#!/usr/bin/env bash

if   type nvim > /dev/null 2>&1; then
  export EDITOR=$(which nvim)
elif type  vim > /dev/null 2>&1; then
  export EDITOR=$(which vim)
elif type  vi  > /dev/null 2>&1; then
  export EDITOR=$(which vi)
fi
